import axios from "axios";
import {resolve} from "@babel/core/lib/vendor/import-meta-resolve";

const BACKEND_URL = 'https://react-native-practice-81ad9-default-rtdb.europe-west1.firebasedatabase.app';

export async function storeExpense(expenseData){
    const response = await axios.post(BACKEND_URL + '/expenses.json',
        //second argument is the value that should sent to the database, in this case it will be an expenseData which is an
        //object of amount decription and date no need for id because a uniqe id will be auto generated by FIREBASE
        expenseData
        //you can add any segments here(expenses) will transform into nodes or folders in the database
        //so this will create an expense node and under it we will find the newlly added expense
        //json is firebase specific
        //post request is for creating new data
        );
    const id = response.data.name;
    //the id generated by firebase is called name
    return id;



}

export async function fetchExpenses(){
    const response = await axios.get(BACKEND_URL + '/expenses.json');
    //modern way to do it is to turn the functionn to async and wait for the data

    const expenses = [];
    console.log(response.data);

    for(const key in response.data){
        const expenseObj = {
            id: key,
            amount: response.data[key].amount,
            date: new Date(response.data[key].date),
            description: response.data[key].description,
        }
        expenses.push(expenseObj);
    }
    return expenses
}